### ISSUE TITLE
Please upgrade Android X

### ISSUE THREAD

**Issue by 370966584** [adtalos/flutter_msa_sdk#3]
![image](https://user-images.githubusercontent.com/26058251/79303261-0c959780-7f21-11ea-80de-5a99e0245ae6.png)

**Comment by andot** [comment]
@370966584 已升级

**Comment by 370966584** [comment]
> @370966584 已升级

![image](https://user-images.githubusercontent.com/26058251/79322218-1af2ac00-7f3f-11ea-958d-21a8765dc418.png)

这个插件是不是只有 Android 10  开始支持的吗

我的手机是Android 9 的  只能获取到OAID

**Comment by andot** [comment]
不是，是跟手机设备有关。我的小米手机是Android 7.1.1，oaid, vaid 和 aaid 三个值都能获取到。不过一般来说，只用 oaid 就够了。

**Comment by 370966584** [comment]
> 不是，是跟手机设备有关。我的小米手机是Android 7.1.1，oaid, vaid 和 aaid 三个值都能获取到。不过一般来说，只用 oaid 就够了。
多谢
