### ISSUE TITLE
打包出来应用闪退

### ISSUE THREAD

**Issue by 50431040** [adtalos/flutter_msa_sdk#6]
minSdkVersion 21
targetSdkVersion 29
minifyEnabled true
shrinkResources true
useProguard true

**Comment by 50431040** [comment]
测试过了，跟混淆没有关系，和下面两个配置有关，只有两个值都为false时不会闪退
minifyEnabled false
shrinkResources false

**Comment by andot** [comment]
应该是msa的包不能混淆造成的。不过这个我也没办法，是msa官方包的问题。

**Comment by 50431040** [comment]
已经解决了，需要添加混淆规则，另外需要更新成最新的1.25的SDK
