### ISSUE TITLE
debug版本能拿到oaid，打包之后的release版本就获取不到了

### ISSUE THREAD

**Issue by 1207915357** [adtalos/flutter_msa_sdk#9]
![image](https://user-images.githubusercontent.com/32265147/109584848-54271100-7b3d-11eb-86a6-34c0fea50aa0.png)
![image](https://user-images.githubusercontent.com/32265147/109584859-5a1cf200-7b3d-11eb-85ac-5a61cb491e55.png)

**Comment by andot** [comment]
这个问题在 oaid sdk 的官方文档中有详细的配置说明，应该是你没有配置混淆规则导致的，可以参考该说明进行配置。

**Comment by 1207915357** [comment]
> 这个问题在 oaid sdk 的官方文档中有详细的配置说明，应该是你没有配置混淆规则导致的，可以参考该说明进行配置。参考 #7

谢谢您的解答!
我在自己项目中 android/app/build.gradle 文件中配置了
` release {
            signingConfig signingConfigs.debug
            minifyEnabled true  //资源压缩设置
            useProguard true    //代码压缩设置
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }`
android/ 目录下增加了 proguard-rules.pro 文件
`-keep class XI.CA.XI.**{*;}
-keep class XI.K0.XI.**{*;}
-keep class XI.XI.K0.**{*;}
-keep class XI.xo.XI.XI.**{*;}
-keep class com.asus.msa.SupplementaryDID.**{*;}
-keep class com.asus.msa.sdid.**{*;}
-keep class com.bun.lib.**{*;}
-keep class com.bun.miitmdid.**{*;}
-keep class com.huawei.hms.ads.identifier.**{*;}
-keep class com.samsung.android.deviceidservice.**{*;}
-keep class com.zui.opendeviceidlibrary.**{*;}
-keep class org.json.**{*;}
-keep public class com.netease.nis.sdkwrapper.Utils {public <methods>;}`

使用 flutter build apk 打包后还是获取不到oaid。
请问还需要再其他地方或者插件源码里面配置吗
